wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 3
      - 5
      4: 3.7.10
      5: 0.10.32
      8:
      - 5
